$(document).ready(function()
{
	$("#contacts_more").click(function()
			{
				$("#contacts").slideToggle("fast");
				$("#contacts_more").hide();
				$("#contacts_less").show();
			});
	$("#contacts_less").click(function()
			{
				$("#contacts").slideToggle("fast");
				$("#contacts_less").hide();
				$("#contacts_more").show();
			});
	$("#preparation_ref_more").click(function()
			{
				$("#preparation_ref").slideToggle("fast");
				$("#preparation_ref_more").hide();
				$("#preparation_ref_less").show();
			});
	$("#preparation_ref_less").click(function()
			{
				$("#preparation_ref").slideToggle("fast");
				$("#preparation_ref_less").hide();
				$("#preparation_ref_more").show();
			});
	$("#second_level_menu_title-01").click(function()
			{
				$("#second_level_menu-01").slideToggle("fast");
				if($("#second_level_menu_image-01").attr('src')=='resources/images/plus-on.png'){
					$("#second_level_menu_image-01").attr("src","resources/images/reduce-on.png");	
				}	
				else{
					$("#second_level_menu_image-01").attr("src","resources/images/plus-on.png");	
				}
			});
	$("#second_level_menu_title-01").mouseover(function()
			{
				if($("#second_level_menu_image-01").attr('src')=='resources/images/plus.png'){
						$("#second_level_menu_image-01").attr("src","resources/images/plus-on.png");	
					}
				if($("#second_level_menu_image-01").attr('src')=='resources/images/reduce.png'){
						$("#second_level_menu_image-01").attr("src","resources/images/reduce-on.png");	
					}		
			});
	$("#second_level_menu_title-01").mouseout(function()
			{
				if($("#second_level_menu_image-01").attr('src')=='resources/images/plus-on.png'){
						$("#second_level_menu_image-01").attr("src","resources/images/plus.png");	
					}
				if($("#second_level_menu_image-01").attr('src')=='resources/images/reduce-on.png'){
						$("#second_level_menu_image-01").attr("src","resources/images/reduce.png");	
					}		
			});
	$("#second_level_menu_title-02").click(function()
			{
				$("#second_level_menu-02").slideToggle("fast");
				if($("#second_level_menu_image-02").attr('src')=='resources/images/plus-on.png'){
					$("#second_level_menu_image-02").attr("src","resources/images/reduce-on.png");	
				}	
				else{
					$("#second_level_menu_image-02").attr("src","resources/images/plus-on.png");	
				}
			});
	$("#second_level_menu_title-02").mouseover(function()
			{
				if($("#second_level_menu_image-02").attr('src')=='resources/images/plus.png'){
						$("#second_level_menu_image-02").attr("src","resources/images/plus-on.png");	
					}
				if($("#second_level_menu_image-02").attr('src')=='resources/images/reduce.png'){
						$("#second_level_menu_image-02").attr("src","resources/images/reduce-on.png");	
					}		
			});
	$("#second_level_menu_title-02").mouseout(function()
			{
				if($("#second_level_menu_image-02").attr('src')=='resources/images/plus-on.png'){
						$("#second_level_menu_image-02").attr("src","resources/images/plus.png");	
					}
				if($("#second_level_menu_image-02").attr('src')=='resources/images/reduce-on.png'){
						$("#second_level_menu_image-02").attr("src","resources/images/reduce.png");	
					}		
			});
	$("#second_level_menu_title-03").click(function()
			{
				$("#second_level_menu-03").slideToggle("fast");
				if($("#second_level_menu_image-03").attr('src')=='resources/images/plus-on.png'){
					$("#second_level_menu_image-03").attr("src","resources/images/reduce-on.png");	
				}	
				else{
					$("#second_level_menu_image-03").attr("src","resources/images/plus-on.png");	
				}
			});
	$("#second_level_menu_title-03").mouseover(function()
			{
				if($("#second_level_menu_image-03").attr('src')=='resources/images/plus.png'){
						$("#second_level_menu_image-03").attr("src","resources/images/plus-on.png");	
					}
				if($("#second_level_menu_image-03").attr('src')=='resources/images/reduce.png'){
						$("#second_level_menu_image-03").attr("src","resources/images/reduce-on.png");	
					}		
			});
	$("#second_level_menu_title-03").mouseout(function()
			{
				if($("#second_level_menu_image-03").attr('src')=='resources/images/plus-on.png'){
						$("#second_level_menu_image-03").attr("src","resources/images/plus.png");	
					}
				if($("#second_level_menu_image-03").attr('src')=='resources/images/reduce-on.png'){
						$("#second_level_menu_image-03").attr("src","resources/images/reduce.png");	
					}		
			});

	$("#second_level_menu_title-04").click(function()
			{
				$("#second_level_menu-04").slideToggle("fast");
				if($("#second_level_menu_image-04").attr('src')=='resources/images/plus-on.png'){
					$("#second_level_menu_image-04").attr("src","resources/images/reduce-on.png");	
				}	
				else{
					$("#second_level_menu_image-04").attr("src","resources/images/plus-on.png");	
				}
			});
	$("#second_level_menu_title-04").mouseover(function()
			{
				if($("#second_level_menu_image-04").attr('src')=='resources/images/plus.png'){
						$("#second_level_menu_image-04").attr("src","resources/images/plus-on.png");	
					}
				if($("#second_level_menu_image-04").attr('src')=='resources/images/reduce.png'){
						$("#second_level_menu_image-04").attr("src","resources/images/reduce-on.png");	
					}		
			});
	$("#second_level_menu_title-04").mouseout(function()
			{
				if($("#second_level_menu_image-04").attr('src')=='resources/images/plus-on.png'){
						$("#second_level_menu_image-04").attr("src","resources/images/plus.png");	
					}
				if($("#second_level_menu_image-04").attr('src')=='resources/images/reduce-on.png'){
						$("#second_level_menu_image-04").attr("src","resources/images/reduce.png");	
					}		
			});

	$("#second_level_menu_title-05").click(function()
			{
				$("#second_level_menu-05").slideToggle("fast");
				if($("#second_level_menu_image-05").attr('src')=='resources/images/plus-on.png'){
					$("#second_level_menu_image-05").attr("src","resources/images/reduce-on.png");	
				}	
				else{
					$("#second_level_menu_image-05").attr("src","resources/images/plus-on.png");	
				}
			});
	$("#second_level_menu_title-05").mouseover(function()
			{
				if($("#second_level_menu_image-05").attr('src')=='resources/images/plus.png'){
						$("#second_level_menu_image-05").attr("src","resources/images/plus-on.png");	
					}
				if($("#second_level_menu_image-05").attr('src')=='resources/images/reduce.png'){
						$("#second_level_menu_image-05").attr("src","resources/images/reduce-on.png");	
					}		
			});
	$("#second_level_menu_title-05").mouseout(function()
			{
				if($("#second_level_menu_image-05").attr('src')=='resources/images/plus-on.png'){
						$("#second_level_menu_image-05").attr("src","resources/images/plus.png");	
					}
				if($("#second_level_menu_image-05").attr('src')=='resources/images/reduce-on.png'){
						$("#second_level_menu_image-05").attr("src","resources/images/reduce.png");	
					}		
			});

	$("#tabs").click(function()
		{	   
         	var val=$('input:radio[name="animal_classification"]:checked').val();
         	if(val=="tra"){
        		$("#tab1").show();
        		$("#tab2").hide();
        		$("#tab3").hide();
        		
         	}
         	if(val=="tar"){
        		$("#tab1").hide();
        		$("#tab2").show();
        		$("#tab3").hide();
             
         	}if(val=="oth"){
        		$("#tab1").hide();
        		$("#tab2").hide();
        		$("#tab3").show();
             
         	}
     	
		});
	$(".physiological_data-select").click(function (e) 
				{ 
					var e_id = $(e.target).attr('id'); 
					$("#text_"+e_id).slideToggle("fast");

		});
	
	$("#edit_image").mouseover(function()
			{
		$("#edit_font").slideToggle("fast");
			});
	$("#edit_image").mouseout(function()
			{
		$("#edit_font").slideToggle("fast");
			});
	$("#face_image").mouseover(function()
			{
		$("#edit_face_font").slideToggle("fast");
			});
	$("#face_image").mouseout(function()
			{
		$("#edit_face_font").slideToggle("fast");
			});
	
	$("#edit_collection_img").mouseover(function()
			{
		$("#edit_collection").slideToggle("fast");
			});
	$("#edit_collection_img").mouseout(function()
			{
		$("#edit_collection").slideToggle("fast");
			});
	
});
